export const data = {
    string: [
        { value: 'Aude' },
        { value: 'Théodule' },
        { value: null },
        { value: 'Clothilde' },
        { value: 'Archibald' },
        { value: 'Bathilde' },
        { value: 'Artaud' },
        { value: 'Hugon' },
        { value: 'Folquet' },
        { value: 'Gaubert' },
        { value: 'Jeanne' },
        { value: 'Bérenger' },
        { value: 'Geneviève' },
        { value: undefined },
        { value: 'Eudes' },
        { value: 'Clotaire' },
        { value: 'Foulques' },
        { value: 'Isabeau' },
        { value: 'Herbert' },
        { value: 'Aliénor' },
        { value: 'Hildebert' },
        { value: 'Berthille' },
        { value: 'Honoré' },
        { value: 'Loup' },
        { value: 'Milon' },
        { value: 'Pépin' },
        { value: 'Willibert' },
        { value: 'Childeric' },
        { value: 'Blanche' }
    ],
    number: [
        { value: 12 },
        { value: 8 },
        { value: 19 },
        { value: 95 },
        { value: 27 },
        { value: 36 },
        { value: null },
        { value: 45 },
        { value: 87 },
        { value: 22 },
        { value: undefined },
        { value: 21 },
        { value: 64 },
        { value: 70 }
    ],
    boolean: [
        { value: true },
        { value: false },
        { value: undefined },
        { value: null },
        { value: true },
        { value: true },
        { value: true },
        { value: false },
        { value: false },
        { value: true },
        { value: false },
        { value: false },
        { value: false },
        { value: undefined },
        { value: true },
        { value: true },
        { value: null }
    ]
};
