export const data = [
    {
        "date": "2025-01-18T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "1",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "1",
        "mcf_export": "0",
        "mcf_run_result": "2",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-19T00:00:00.000Z",
        "users_expert": "0",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-20T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "3",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-21T00:00:00.000Z",
        "users_expert": "0",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-22T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "4",
        "local_public": "0",
        "statistic_expert": "1",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-23T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "23",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "4",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-24T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "3",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-25T00:00:00.000Z",
        "users_expert": "0",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-26T00:00:00.000Z",
        "users_expert": "0",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-27T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "1",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "3",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-28T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "10",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-29T00:00:00.000Z",
        "users_expert": "4",
        "users_public": "0",
        "local_expert": "14",
        "local_public": "0",
        "statistic_expert": "1",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "1",
        "layers_public": "0",
        "mcf_run": "1",
        "mcf_export": "1",
        "mcf_run_result": "83",
        "mcf_export_result": "83"
    },
    {
        "date": "2025-01-30T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "5",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "2",
        "territory_public": "0",
        "layers_expert": "1",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-01-31T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "4",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-01T00:00:00.000Z",
        "users_expert": "0",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-02T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "2",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-03T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "7",
        "local_public": "0",
        "statistic_expert": "6",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-04T00:00:00.000Z",
        "users_expert": "4",
        "users_public": "0",
        "local_expert": "55",
        "local_public": "0",
        "statistic_expert": "11",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-05T00:00:00.000Z",
        "users_expert": "3",
        "users_public": "1",
        "local_expert": "13",
        "local_public": "0",
        "statistic_expert": "3",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "1",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-06T00:00:00.000Z",
        "users_expert": "4",
        "users_public": "1",
        "local_expert": "98",
        "local_public": "0",
        "statistic_expert": "3",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "1",
        "layers_public": "0",
        "mcf_run": "1",
        "mcf_export": "0",
        "mcf_run_result": "4329",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-07T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "12",
        "local_public": "0",
        "statistic_expert": "1",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "1",
        "layers_public": "0",
        "mcf_run": "1",
        "mcf_export": "1",
        "mcf_run_result": "4329",
        "mcf_export_result": "4329"
    },
    {
        "date": "2025-02-08T00:00:00.000Z",
        "users_expert": "0",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-09T00:00:00.000Z",
        "users_expert": "0",
        "users_public": "0",
        "local_expert": "0",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-10T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "1",
        "local_public": "0",
        "statistic_expert": "1",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "1",
        "mcf_export": "1",
        "mcf_run_result": "4329",
        "mcf_export_result": "4329"
    },
    {
        "date": "2025-02-11T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "2",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-12T00:00:00.000Z",
        "users_expert": "1",
        "users_public": "0",
        "local_expert": "121",
        "local_public": "0",
        "statistic_expert": "2",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-13T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "7",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-14T00:00:00.000Z",
        "users_expert": "5",
        "users_public": "0",
        "local_expert": "45",
        "local_public": "0",
        "statistic_expert": "8",
        "statistic_public": "0",
        "territory_expert": "1",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    },
    {
        "date": "2025-02-15T00:00:00.000Z",
        "users_expert": "2",
        "users_public": "0",
        "local_expert": "3",
        "local_public": "0",
        "statistic_expert": "0",
        "statistic_public": "0",
        "territory_expert": "0",
        "territory_public": "0",
        "layers_expert": "0",
        "layers_public": "0",
        "mcf_run": "0",
        "mcf_export": "0",
        "mcf_run_result": "0",
        "mcf_export_result": "0"
    }
]