export const data = [{"id":1,"product":"Coffee Cup 16oz Foam","price":58.64},
{"id":2,"product":"Turnip - Wax","price":46.51},
{"id":3,"product":"Hinge W Undercut","price":41.58},
{"id":4,"product":"Coconut - Shredded, Unsweet","price":38.4},
{"id":5,"product":"Coffee - French Vanilla Frothy","price":15.39},
{"id":6,"product":"Straws - Cocktale","price":70.69},
{"id":7,"product":"Cheese Cloth No 100","price":49.55},
{"id":8,"product":"Tart - Butter Plain Squares","price":99.54},
{"id":9,"product":"Chickensplit Half","price":85.75},
{"id":10,"product":"Bread - Corn Muffaletta","price":67.95},
{"id":11,"product":"Halibut - Fletches","price":52.52},
{"id":12,"product":"Cinnamon Rolls","price":21.75},
{"id":13,"product":"Lettuce - Escarole","price":93.25},
{"id":14,"product":"Water - Spring Water 500ml","price":51.9},
{"id":15,"product":"Gelatine Leaves - Bulk","price":50.27},
{"id":16,"product":"Onions - Dried, Chopped","price":6.86},
{"id":17,"product":"Ecolab Crystal Fusion","price":49.43},
{"id":18,"product":"Grapefruit - White","price":12.24},
{"id":19,"product":"Octopus - Baby, Cleaned","price":29.76},
{"id":20,"product":"Beef - Tenderloin","price":49.36},
{"id":21,"product":"Cookies Oatmeal Raisin","price":56.17},
{"id":22,"product":"Beef Tenderloin Aaa","price":93.43},
{"id":23,"product":"Momiji Oroshi Chili Sauce","price":25.9},
{"id":24,"product":"Juice - Propel Sport","price":26.08},
{"id":25,"product":"Sponge Cake Mix - Chocolate","price":31.02},
{"id":26,"product":"Pasta - Agnolotti - Butternut","price":51.31},
{"id":27,"product":"Ice Cream - Super Sandwich","price":53.63},
{"id":28,"product":"Syrup - Monin - Blue Curacao","price":16.7},
{"id":29,"product":"Cod - Salted, Boneless","price":88.7},
{"id":30,"product":"Crab - Soft Shell","price":59.07},
{"id":31,"product":"Lemon Grass","price":32.83},
{"id":32,"product":"Soup - Campbells Chicken","price":74.11},
{"id":33,"product":"Quail - Jumbo Boneless","price":44.44},
{"id":34,"product":"Urban Zen Drinks","price":91.94},
{"id":35,"product":"Daves Island Stinger","price":22.02},
{"id":36,"product":"Oil - Cooking Spray","price":63.76},
{"id":37,"product":"Onions - Dried, Chopped","price":6.24},
{"id":38,"product":"Dip - Tapenade","price":68.71},
{"id":39,"product":"Carbonated Water - Cherry","price":96.25},
{"id":40,"product":"Vinegar - Tarragon","price":88.34},
{"id":41,"product":"Bar - Granola Trail Mix Fruit Nut","price":43.28},
{"id":42,"product":"Cheese Cheddar Processed","price":15.64},
{"id":43,"product":"Mussels - Cultivated","price":85.52},
{"id":44,"product":"Straw - Regular","price":4.4},
{"id":45,"product":"Wine - Periguita Fonseca","price":9.76},
{"id":46,"product":"Flour - Semolina","price":10.62},
{"id":47,"product":"Cake - Cheese Cake 9 Inch","price":49.48},
{"id":48,"product":"Vacuum Bags 12x16","price":11.06},
{"id":49,"product":"Cookie Choc","price":6.37},
{"id":50,"product":"Island Oasis - Banana Daiquiri","price":58.46}]