export const comparator = {
    string: [
        { value: 'Aude' },
        { value: 'Théodule' },
        { value: null },
        { value: 'Clothilde' },
        { value: 'Archibald' },
        { value: 'Bathilde' },
        { value: 'Artaud' },
        { value: 'Hugon' },
        { value: 'Folquet' },
        { value: 'Gaubert' },
        { value: 'Jeanne' },
        { value: 'Bérenger' },
        { value: 'Geneviève' },
        { value: undefined },
        { value: 'Eudes' },
        { value: 'Clotaire' },
        { value: 'Foulques' },
        { value: 'Isabeau' },
        { value: 'Herbert' },
        { value: 'Aliénor' },
        { value: 'Hildebert' },
        { value: 'Berthille' },
        { value: 'Honoré' },
        { value: 'Loup' },
        { value: 'Milon' },
        { value: 'Pépin' },
        { value: 'Willibert' },
        { value: 'Childeric' },
        { value: 'Blanche' }
    ],
    number: [
        { value: 12 },
        { value: 8 },
        { value: 19 },
        { value: 95 },
        { value: 27 },
        { value: 36 },
        { value: null },
        { value: 45 },
        { value: 87 },
        { value: 22 },
        { value: undefined },
        { value: 21 },
        { value: 64 },
        { value: 70 }
    ],
    boolean: [
        { value: true },
        { value: false },
        { value: undefined },
        { value: null },
        { value: true },
        { value: true },
        { value: true },
        { value: false },
        { value: false },
        { value: true },
        { value: false },
        { value: false },
        { value: false },
        { value: undefined },
        { value: true },
        { value: true },
        { value: null }
    ]
}

export const mcf_basic = [{"id":1,"task":"nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient","priority":"medium"},
{"id":2,"task":"posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet","priority":"medium"},
{"id":3,"task":"morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices","priority":"medium"},
{"id":4,"task":"consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum","priority":"low"},
{"id":5,"task":"purus phasellus in felis donec","priority":"high"},
{"id":6,"task":"turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus","priority":"high"},
{"id":7,"task":"penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus","priority":"high"},
{"id":8,"task":"pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna","priority":"high"},
{"id":9,"task":"non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac","priority":"low"},
{"id":10,"task":"eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan","priority":"high"},
{"id":11,"task":"quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa","priority":"low"},
{"id":12,"task":"tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh","priority":"high"},
{"id":13,"task":"nec condimentum neque sapien placerat ante nulla justo aliquam quis","priority":"medium"},
{"id":14,"task":"mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem","priority":"medium"},
{"id":15,"task":"luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec","priority":"low"},
{"id":16,"task":"in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam","priority":"medium"},
{"id":17,"task":"gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae","priority":"low"},
{"id":18,"task":"risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero","priority":"low"},
{"id":19,"task":"tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla","priority":"low"},
{"id":20,"task":"aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque","priority":"medium"}]

